controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    interpolation_method: none          # 🔑 Disable spline interpolation
    allow_nonzero_velocity_at_trajectory_end: true
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      - gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
